import Vue from 'vue'
import '@/main.styl'
import colors from 'vuetify/lib/util/colors'
import Vuetify, {
  VApp,
  VBtn,
  VCard,
  VCardText,
  VCardTitle,
  VContainer,
  VContent,
  VFlex,
  VFooter,
  VIcon,
  VLayout,
  VList,
  VListTile,
  VListTileTitle,
  VMenu,
  VParallax,
  VSpacer,
  VToolbar,
  VToolbarItems,
  VToolbarTitle,
} from 'vuetify/lib'

Vue.use(Vuetify, {
  iconfont: 'mdi',
  components: {
    VApp,
    VBtn,
    VCard,
    VCardText,
    VCardTitle,
    VContainer,
    VContent,
    VFlex,
    VFooter,
    VIcon,
    VLayout,
    VList,
    VListTile,
    VListTileTitle,
    VMenu,
    VParallax,
    VSpacer,
    VToolbar,
    VToolbarItems,
    VToolbarTitle,
  },
  theme: {
    primary: colors.deepPurple.base,
    secondary: colors.pink.base,
    accent: colors.purple.base,
    error: colors.red.base,
    warning: colors.amber.base,
    info: colors.cyan.base,
    success: colors.lightGreen.base,
  },
})
